### ISSUE TITLE
myget dev package publishing is broken

### ISSUE THREAD

**Issue by bahusoid** [nhibernate/nhibernate-core#3112]
Seems publishing dev builds is broken for some time:
https://teamcity.jetbrains.com/buildConfiguration/NHibernate_NHibernatePublishNuGet?mode=branches

Error:
```
Response status code does not indicate success: 413 (The total packages size for the pending uploads is too large. The feed owner may have to upgrade the MyGet subscription to resolve this issue.)
```

https://docs.myget.org/docs/reference/faq#I_get_a_413_RequestEntityTooLarge_when_pushing_packages_to_my_MyGet_feed

**Comment by hazzik** [comment]
I've changed retention rules to keep only 10 newest packages. Should help a bit.

**Comment by bahusoid** [comment]
>  only 10 newest packages

Isn't it too few? What storage quota do you have? 1 Gb? It seems it should handle 50 packages..

**Comment by hazzik** [comment]
> What storage quota do you have?

500Mb

**Comment by bahusoid** [comment]
Same [issue](https://teamcity.jetbrains.com/buildConfiguration/NHibernate_NHibernatePublishNuGet/4101345?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandBuildChangesSection=true): 
> Response status code does not indicate success: 413 (The total packages size for the pending uploads is too large. The feed owner may have to upgrade the MyGet subscription to resolve this issue.).

Am why only 500 Mb? It claims 1Gb quota for open-source project (which kinda sucks too)

I think we should move some place else. Cloudsmith offers 50Gb - https://help.cloudsmith.io/docs/open-source-hosting-policy

**Comment by fredericDelaporte** [comment]
It seems to be not solved yet. And the ten package retention rules seems not applied either, since it lists around 45 packages. With our current package size and a 500 Mb limit, we can only keep 40 of them, let's even say only 30 to be safe.

I have an account on MyGet, `fredericdelaporte`. Hazzik, may you add me rights on the NHibernate MyGet feed?

**Comment by hazzik** [comment]
> Hazzik, may you add me rights on the NHibernate MyGet feed?

I could not find how to do that.

> Let's see what will be the outcome of MyGet

No response from them. Let's migrate to Cloudsmith

**Comment by hazzik** [comment]
@fredericDelaporte @bahusoid 

> Hazzik, may you add me rights on the NHibernate MyGet feed?

I could not find how to do that.

> Let's see what will be the outcome of MyGet

No response from them. Let's migrate to Cloudsmith

**Comment by bahusoid** [comment]
> Let's migrate to Cloudsmith

Done.

https://cloudsmith.io/~nhibernate/repos/nhibernate-core/packages/

One package is already deployed.

Invites are sent to you.

**Comment by bahusoid** [comment]
It would also be good to assign higher priority for publish build configuration https://teamcity.jetbrains.com/viewType.html?buildTypeId=NHibernate_NHibernatePublishNuGet&tab=buildTypeSettings
As currently it's added to the end of queue. See https://www.jetbrains.com/help/teamcity/working-with-build-queue.html#Managing+Build+Priorities

I have no rights to do it (seems need to ask teamcity)

**Comment by fredericDelaporte** [comment]
I get around this at teamcity by running custom builds with top priority when I do the publishing of a new version of NHibernate.

**Comment by bahusoid** [comment]
Fixed by #3275

**Comment by fredericDelaporte** [comment]
I had a look to the NuGet build: it depends on the NHibernate Release Build, which is not triggered by changes only: it runs only at a fixed schedule. That allows to run it less frequently than other builds. The idea is likely that it is not a test build, but one for generating the artificats, which we do not need to do at each change when a PR is more or less WIP. And since our teamcity agent is lone machine taking time to run all the builds it has, sparing a few builds makes sense.

**Comment by bahusoid** [comment]
> I had a look to the NuGet build: it depends on the NHibernate Release Build, which is not triggered by changes only: it runs only at a fixed schedule.

Is it about assigning higher priority or what? I know about schedule. Nuget build depends on NHIbernate Release Build but triggered build is queued as common build and placed at the end of queue (so can be executed hours later after release build - after other builds from queue are processed) With higher priority it will be placed at the top of queue and will be executed soon after Release build.

**Comment by fredericDelaporte** [comment]
Its [trigger](https://teamcity.jetbrains.com/admin/editTriggers.html?id=buildType:NHibernate_NHibernateReleasePackage) is different from other builds (example: [Firebird](https://teamcity.jetbrains.com/admin/editTriggers.html?id=buildType:bt874)). It is not low priority, it is fixed schedule, which result in it being build a lot less, and usually much later than others builds.

**Comment by bahusoid** [comment]
It seems we are still not on the same page. It's not important how rare release build is triggered. And It's not about priority of release build. It's about [nuget build](https://teamcity.jetbrains.com/buildConfiguration/NHibernate_NHibernatePublishNuGet) 
 which is triggered by release build and the time it takes to be actually started after it's been triggered. Currently after nuget build is triggered (no matter how rare it is) it could take hours till it's actually executed due to other builds in queue. 
I want to make nuget build high priority so it's executed right after release build and don't hang in queue for hours.
